### ISSUE TITLE
Update _diagnostics heatmap for SK

### ISSUE THREAD

**Issue by rcalvo12** [JMSLab/BootstrapReport#16]
In this issue, we will edit the diagnostics so that we can make a heatmap for SKD.

**Comment by rcalvo12** [comment]
Thread continues in #17

**Comment by MosesStewart** [comment]
In this issue we  . . .

-  Edited the heatmap function in `_diagnostics.py` to allow users to make heatmaps using the SK distance as well as the TV distance.
- Added a `bounds` and `vrange` argument so that users can zoom into the plot with more control and control the color scaling of the heatmap. 

Changes made into `main` 1f327a7 !
